config/routes.rb
#- Copyright 2011 Strange Loop LLC
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-    http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.
#-



Conf::Application.routes.draw do


  devise_for :attendee_creds, :controllers => { :registrations => 'attendee_cred/registrations' } do
    get '/login' => 'devise/sessions#new', :as => :new_attendee_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_attendee_session
    get '/activation/:token', :to => 'devise/registrations#new', :as => :activation
    match '/connect' => 'attendees#index', :as => :attendee_cred_root
  end

  resource :attendee, :only => [:edit]
  resources :attendees, :only => [:index], :path => "/connect"
  resources :talks

  get '/stream', :to => 'stream#show'
  get '/streamtheater', :to => 'stream_theater#show'

  put '/connect/update', :to => 'attendees#update'
  get '/connect/:id', :to => 'attendees#show', :as => :attendee

  match '/media/*dragonfly', :to => Dragonfly[:strangeloop]

  match '/blog/:year/:month/:day/:id' => redirect('/news/%{year}/%{month}/%{day}/%{id}')
  match '/news/:year/:month/:day/:id' => 'news_items#show'
  match '/blog/stloopadm' => redirect('/news')
  match '/blog' => redirect('/news')



end

app/views/shared/_content_page.html.erb
<%
  # provide a default array for collecting CSS for sections
  css = []
  page = @page

  # if 'sections' is passed in as a local_assigns, all of this is ignored.
  if local_assigns[:sections].blank?
    # always have a title
    sections = [{:yield => :body_content_title, :fallback => page_title, :title => true}]

    # append sections from this page.
    page.parts.inject(sections) do |s, part|
      # we have some default yields, body_content_left and body_content_right
      # these map to 'body' and 'side_body' fields in default Refinery.
      section = {:fallback => part.body}
      section[:yield] = case (title_symbol = part.title.to_s.gsub(/\ /, '').underscore.to_sym)
        when :body then :body_content_left
        when :side_body then :body_content_right
        else title_symbol
        end

      # add section to the list unless we were specifically requested not to.
      # otherwise, add css saying it's been removed.
      unless (local_assigns[:hide_sections]||=[]).include?(section[:yield])
        s << section
      else
        css << "no_#{section[:yield]}"
      end
    end unless page.nil? or page.parts.blank?

    # Ensure that even without @page.parts we still have body_content_left and body_content_right
    all_yields = sections.collect{|s| s[:yield]}
    sections << {:yield => :body_content_left} unless all_yields.include?(:body_content_left)
    sections << {:yield => :body_content_right} unless all_yields.include?(:body_content_right)
  end

  # you can add more sections to the list using something like this:
  # sections |= [{:yield => :something_else, :fallback => another_method, :id => 'something'}]

  sections.each do |section|
    section[:html] = yield(section[:yield]) if section[:yield].present?

    if section[:html].blank? and !local_assigns[:show_empty_sections] and
       !local_assigns[:remove_automatic_sections] and section.keys.include?(:fallback) and
       section[:fallback].present?
      section[:html] = raw(section[:fallback])
    end

    dom_id = section[:id] || section[:yield]
    if section[:html].present?
      if section[:title]
        section[:html] = <<-eos
<div class='row_top_tile_sub'>
  <div class='container_12'>
    <div class='grid_8'>
      <div class='page_title'>#{section[:html]}</div>
    </div>
  </div>
</div>
eos
      else
        section[:html] = "<section id='#{dom_id}'><div class='inner'>#{section[:html]}</div></section>"
      end
    else
      css << "no_#{dom_id}"
    end
  end
-%>
<section id='body_content'<%= " class='#{css.join(' ')}'" if css.present? %>>
  <%= raw sections.map{|section| section[:html]}.join("\n") -%>
</section>
<%= render '/shared/draft_page_message' unless page.nil? or page.live? -%>

app/views/shared/_current_attendee.html.erb
<%= javascript_tag "
var username = \"#{username}\",
    attendee_login_enabled = \"true\",
    attendee_path = \"#{attendee_path}\",
    login_path = \"#{main_app.new_attendee_session_path}\",
    logout_path = \"#{main_app.destroy_attendee_session_path}\";" %>

app/views/shared/_flash.html.erb
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>

app/views/shared/_footer.html.erb
<% cache('footer') do -%>
<div class="foot">
  <div class="footer">
    <div class="copy">
      <%= t('.copyright1') -%> &copy; <%= t('.copyright2', :year => Time.now.year,
                                            :site_name => Refinery::Setting.find_or_set(:site_name, "Strange Loop")) %>
      <p></p>
      <%= raw t('.attribution') %>
    </div>

    <% link_tree(refinery_menu_pages).reverse.each do |page_group| -%>
    <div class="footer_box resources_box">
      <%= render :partial => 'shared/footer_menu', :collection => page_group %>
    </div>
    <% end -%>
  </div>
</div>
<% end -%>

app/views/shared/_footer_menu.html.erb
<% if footer_menu.parent_id.nil? -%>
  <div class="footer_box_header">
     <h4><%= link_to footer_menu.title, footer_menu.url %></h4>
  </div>

  <div class="bottom_box">
    <ul>
      <li>
        <ul>
          <% footer_menu.children.each do |child| -%>
            <li>
              <%= link_to(child.url) do %>
              <span><%= child.title %></span>
              <% end -%>
            </li>
          <% end -%>
        </ul>
      </li>
    </ul>
  </div>
<% end -%>

app/views/shared/_formtastic.html.erb
<% content_for :stylesheets do -%>
  <%= stylesheet_link_tag 'formtastic' %>
  <%= stylesheet_link_tag 'formtastic_changes' %>
<% end -%>

app/views/shared/_head.html.erb
<%
  if (yielded_head = yield(:head)).present?
    logger.warn "\n-- DEPRECATION WARNING --"
    logger.warn "The use of 'content_for :head' is DEPRECATED for the frontend layouts."
    logger.warn "For stylesheets, use content_for :stylesheets"
    logger.warn "For javascripts, use content_for :javascripts"
    logger.warn "For meta tags, use content_for :meta"
    logger.warn "This change is necessary so that we can deliver a performant experience for the user."
    logger.warn "Called from: #{caller.detect{|c| c =~ %r{#{Rails.root.to_s}}}.inspect.to_s.split(':in').first}\n\n"
  end
  if (yielded_head_libraries = yield(:head_libraries)).present?
    logger.warn "\n-- DEPRECATION WARNING --"
    logger.warn "The use of 'content_for :head_libraries' is DEPRECATED for the frontend layouts."
    logger.warn "Please use content_for :before_javascript_libraries or content_for :after_javascript_libraries instead."
    logger.warn "This change is necessary so that we can deliver a performant experience for the user."
    logger.warn "Called from: #{caller.detect{|c| c =~ %r{#{Rails.root.to_s}}}.inspect.to_s.split(':in').first}\n\n"
  end
%>
<head>
  <meta charset='<%= Conf::Application.config.encoding %>' />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title><%= browser_title(yield(:title)) %></title>
  <%= raw "<meta name=\"description\" content=\"#{@meta.meta_description}\" />" if @meta.meta_description.present? -%>
  <%= raw "<meta name=\"keywords\" content=\"#{@meta.meta_keywords}\">" if @meta.meta_keywords.present? -%>
  <%= csrf_meta_tag if Refinery::Setting.find_or_set(:authenticity_token_on_frontend, true)-%>
  <%= yield :meta %>

  <%= yield :stylesheets %>
  <%= render :partial => '/shared/google_analytics' unless local_request? %>

  <% #TODO: REMOVE yielded_head and yielded_head_libraries and deprecation notice 0.9.9 <=> 1.0 %>
  <%= yielded_head_libraries %>
  <%= yielded_head %>
</head>

app/views/shared/_header.html.erb
<% cache('header') do -%>
<div class="logo">
  <%= link_to image_tag('logo2.png', :alt => Refinery::Setting.find_or_set(:site_name, "Strange Loop")) , root_path %>
</div>
<%= render "/refinery/menu", :dom_id => 'menu', :css => 'menu' -%>

<% end -%>
<% if Refinery::Setting.find_or_set(:attendee_login_enabled, 'false').to_s =~ /true/ -%>
  <%= render '/shared/current_attendee', :username => current_attendee.try(:full_name),
    :attendee_path => (current_attendee ? attendee_path(current_attendee) : ''),
    :login_path => main_app.new_attendee_cred_session_path,
    :logout_path => main_app.destroy_attendee_cred_session_path %>
<% end -%>

app/views/shared/_menu.html.erb
<%
  dom_id ||= 'menu'
  css ||= 'menu'
  hide_children = Refinery::Setting.find_or_set(:menu_hide_children, false) if hide_children.nil?
  # Select top menu items unless 'roots' is supplied.
  collection ||= @menu_pages
  caching = ((defined?(cache_menu) && cache_menu) || Refinery::Setting.find_or_set(:cache_menu, false)) && File.writable?(Rails.cache.cache_path)
  cache_if(caching && !user_signed_in?, [Refinery.base_cache_key, "pages_menus", dom_id, Globalize.locale, request.path].join('_')) do
    if (roots ||= collection.select{|p| p.parent_id.nil?}).present?
      # In order to match items that aren't shown in menu and highlight their associations.
      # This can be supplied if the logic is different in your case.
      unless defined?(selected_item)
        selected_item = collection.detect{|page| selected_page?(page)}
        selected_item ||= @page
      end
  -%>
      <nav id='<%= dom_id %>' class='<%= %W(#{css} clearfix).join(' ') %>'>
        <ul class="sf-menu">
          <%= render :partial => "/shared/menu_branch",
                     :collection => roots,
                     :locals => {
                       :hide_children => hide_children,
                       :sibling_count => (roots.length - 1),
                       :collection => collection,
                       :selected_item => selected_item,
                       :apply_css => true #if you don't care about class='first' class='last' or class='selected' set apply_css to false for speed.
                     }
          -%>
        </ul>
      </nav>
  <% end -%>
<% end -%>

app/views/shared/_menu_branch.html.erb
<%
  if !!local_assigns[:apply_css] and (classes = css_for_menu_branch(menu_branch, menu_branch_counter, sibling_count||=nil, collection, selected_item ||= nil)).any?
    css = "class='#{classes.join(' ')}'"
  end
  dom_id = ("id='item_#{menu_branch_counter}'" if menu_branch.parent_id.nil? and menu_branch.title.present?)

  hide_children = (defined?(hide_children) && hide_children)
  children = if (hide_children || !menu_branch.has_descendants?)
    []
  else
    collection.select { |p| p.parent_id == menu_branch.id }
  end
-%>
<li<%= ['', css, dom_id].compact.join(' ').gsub(/\ *$/, '') %>>
  <%= link_to content_tag(:span, menu_branch.title), menu_branch.url -%>
  <% if children.present? -%>
    <ul class='clearfix'>
      <%=
        render :partial => "/shared/menu_branch",
               :collection => children,
               :locals => {
                 :apply_css => local_assigns[:apply_css],
                 :hide_children => hide_children,
                 :collection => collection,
                 :selected_item => selected_item,
                 :sibling_count => children.size - 1
               } -%>
    </ul>
  <% end -%>
</li>

app/views/shared/_old_menu.html.erb
<%
  dom_id ||= 'menu'
  css ||= 'menu'
  hide_children = Refinery::Setting.find_or_set(:menu_hide_children, false) if hide_children.nil?
  # Select top menu items unless 'roots' is supplied.
  collection ||= refinery_menu_pages
  caching = ((defined?(cache_menu) && cache_menu) || Refinery::Setting.find_or_set(:cache_menu, false)) && File.writable?(Rails.cache.cache_path)
  cache_if(caching && !refinery_user_signed_in?, [Refinery::Core.base_cache_key, "pages_menus", dom_id, Globalize.locale, request.path].join('_')) do
    if (roots ||= collection.select{|p| p.parent_id.nil?}).present?
      # In order to match items that aren't shown in menu and highlight their associations.
      # This can be supplied if the logic is different in your case.
      unless defined?(selected_item)
        selected_item = collection.detect{|page| selected_page?(page)}
        selected_item ||= @page
      end
  -%>
      <nav id='<%= dom_id %>' class='<%= %W(#{css} clearfix).join(' ') %>'>
        <ul class="sf-menu">
          <%= render :partial => "/shared/menu_branch",
                     :collection => roots,
                     :locals => {
                       :hide_children => hide_children,
                       :sibling_count => (roots.length - 1),
                       :collection => collection,
                       :selected_item => selected_item,
                       :apply_css => true #if you don't care about class='first' class='last' or class='selected' set apply_css to false for speed.
                     }
          -%>
        </ul>
      </nav>
  <% end -%>
<% end -%>

app/views/shared/_schedule.html.erb
<div class="container_12">
  <% schedule_sessions.each_pair do |session_day, session_times| %>
    <div class="p3">
      <h3><%= session_day %></h3>
      <% session_times.each_pair do |session_time, sessions| %>
        <ul class="free clearfix">
          <li class="column1" style="line-height: <%= time_column_height sessions.size %>%">
            <%= time_period_for session_time %>
          </li>
          <% sessions.each do |session| %>
            <% if defined?(cache_key) && show_schedule_selection?(cache_key) -%>
            <li title="Click to Attend" class="list-selector miss attend" id="<%= session.id %>">
              <%= image_tag 'loader.gif', :class => 'hidden loading' %>
            </li>
            <% end -%>
            <li class="column3 shadeable" data-track="<%= track_name session %>">
              <div class="title"><%= link_to session.talk.title, session %></div>
              <span class="speaker"><%= speaker_for session.talk, true %></span> &middot;
              <span class="room"><%= room_for session %></span>
              <% if (defined?(display_track) && display_track) && is_technical_track?(session) %>
              &middot;
              <span class="track" style="background: #<%= track_color session %>"><%= track_name session %></span>
            <% end -%>
            </li>
          <% end -%>
        </ul>
      <% end -%>
    </div>
  <% end -%>
</div>

app/views/shared/_schedule_table.html.erb
<div class="container_13">
  <% schedule_sessions.each_pair do |session_day, session_start_hours| %>
    <% room_names = room_names_for(session_day, formats) %>
    <%- next if room_names.empty? %>
    <div class="p3">
      <h3><%= session_day %></h3>
        <ul class="free clearfix schedule-header">
          <% room_names.each do |room| %>
            <li class="header"><%= room %></li>
          <% end%>
        </ul>
      <% session_start_hours.each_pair do |session_start_hour, room_sessions| %>
        <% row_height_class = row_height(room_sessions, room_names) %>
        <ul class="free clearfix schedule <%= row_height_class %>">
          <li class="column1 table-column1-<%= row_height_class %>">
            <div class="time-period-<%= row_height_class %>">
            <%= time_period_for_sessions room_sessions %>
            </div>
          </li>

          <% room_names.each do |room_name| %>
            <li class="cell">
              <%= render :partial => 'shared/schedule/session', :collection => room_sessions[room_name], :locals => {:display_track => display_track, :cache_key => (defined?(cache_key) ? cache_key : 'schedule') } %>
            </li>
          <% end -%>
        </ul>
      <% end -%>
    </div>
  <% end -%>
</div>

app/views/shared/_title.html.erb
<div class="row_top_tile_sub">
  <div class="container_12">
    <div class="grid_12">
      <div class="page_title">
        <%= title %>
      </div>
    </div>
  </div>
</div>