config/routes.rb
#- Copyright 2011 Strange Loop LLC
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-    http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.
#-



Conf::Application.routes.draw do


  devise_for :attendee_creds, :controllers => { :registrations => 'attendee_cred/registrations' } do
    get '/login' => 'devise/sessions#new', :as => :new_attendee_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_attendee_session
    get '/activation/:token', :to => 'devise/registrations#new', :as => :activation
    match '/connect' => 'attendees#index', :as => :attendee_cred_root
  end

  resource :attendee, :only => [:edit]
  resources :attendees, :only => [:index], :path => "/connect"
  resources :talks

  get '/stream', :to => 'stream#show'
  get '/streamtheater', :to => 'stream_theater#show'

  put '/connect/update', :to => 'attendees#update'
  get '/connect/:id', :to => 'attendees#show', :as => :attendee

  match '/media/*dragonfly', :to => Dragonfly[:strangeloop]

  match '/blog/:year/:month/:day/:id' => redirect('/news/%{year}/%{month}/%{day}/%{id}')
  match '/news/:year/:month/:day/:id' => 'news_items#show'
  match '/blog/stloopadm' => redirect('/news')
  match '/blog' => redirect('/news')



end

app/models/attendee.rb
#- Copyright 2011 Strange Loop LLC
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-    http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.
#-

class Attendee < ActiveRecord::Base
  include Gravtastic
  extend FriendlyId

  acts_as_indexed :fields => [:conf_year]
  gravtastic

  @@activation_key = YAML::load_file('config/activation.yml')["activation_key"]

  attr_protected :reg_id, :attendee_cred_id, :conf_year

  has_and_belongs_to_many :conference_sessions,
                          :uniq => true

  belongs_to :attendee_cred
  [:first_name, :last_name, :email, :reg_id].each do |field|
    validates field, :presence => true
  end

  validates :email, :uniqueness => true, :allow_nil => false

  before_create AddConfYear

  friendly_id :full_name, :use => :slugged

  scope :current_year, lambda { where('conf_year' => maximum('conf_year')).order('last_name ASC', 'first_name ASC') }

  def session_calendar
    RiCal.Calendar do |cal|
      conference_sessions.each do |session|
        cal.event do |e|
          e.summary     = session.title
          e.description = session.description
          e.dtstart     = convert_to_cst session.start_time
          e.dtend       = convert_to_cst session.end_time
          e.location    = session.location
          e.url         = session.url
        end
      end
    end
  end

  def convert_to_cst(datetime)
    "TZID=America/Chicago:#{datetime.strftime('%Y%m%dT%H%M%S')}"
  end

  def twitter_id=(name)
    self[:twitter_id] = name.try(:gsub, '@', '')
  end

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def remove_newlines(s)
    s.gsub(/\n/,'')
  end

  def sorted_interested_sessions
    conference_sessions.by_session_time
  end

  #returns false if the supplied id was removed from this attendees sessions list
  #returns true if the supplied id was added to this attendees sessions list
  #returns nil if an invalid session_id was supplied
  def toggle_session(session_id)
    if conference_session_ids.include? session_id
      conference_sessions.delete ConferenceSession.find(session_id)
      return false
    end
    begin
      conference_sessions << ConferenceSession.find(session_id)
      true
    rescue ActiveRecord::RecordNotFound
    end
  end

  def self.existing_attendee?(reg_id)
    Attendee.where("reg_id = ?", reg_id).first
  end

  def register_attendee

    db_attendee  = Attendee.existing_attendee?(reg_id)
    if !db_attendee
      build_attendee_cred({:email => email,
                            :password => SecureRandom.hex(10)})
      save!
      self
    else
      db_attendee
    end
  end
end

app/controllers/attendees_controller.rb
require_relative 'application_controller'

class AttendeesController < ApplicationController
  before_filter :authenticate_attendee_cred!
  respond_to :html, :ics, :only => :show

  expose(:attendee)

  expose(:current_year_attendees) {
    Attendee.current_year.paginate :page => params[:page], :per_page => 60
  }

  expose(:schedule_sessions) { attendee.sorted_interested_sessions }

  def show
    respond_to do |format|
      format.html
      format.ics { render :layout => false, :text => attendee.session_calendar.export }
    end
  end

  def update
    begin
      current_attendee.update_attributes! params[:attendee]
      flash[:notice] = 'Update successful'
    rescue StandardError => issue
      flash[:alert] = "The update failed#{issue.message.gsub('Validation failed', '')}"
    end
    redirect_to current_attendee
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
  def full_name(user)
    Attendee.find_by_attendee_cred_id(user.id).try(:full_name) || ''
  end

  def schedule_partial(attendee)
    attendee.conference_sessions.empty? ? no_schedule(attendee) : 'populated_schedule'
  end

  def is_current_attendee?(attendee)
    current_attendee_cred == attendee.attendee_cred
  end

  def company_link(attendee)
    return '' unless attendee.company
    return attendee.company unless attendee.company_url
    link_to attendee.company, attendee.company_url
  end

  private
  def no_schedule(attendee)
    is_current_attendee?(attendee) ? 'no_schedule' : 'no_schedule_visitor'
  end

end

app/views/attendees/_attendee.html.erb
<div id="main" class="shape">
  <div class="container_12">
  <%= render '/shared/flash', :flash => flash %>

    <div class="grid_11 pad3">
      <div class="pic">
        <%= image_tag attendee.gravatar_url %>
      </div>

      <h3><%= attendee.full_name %></h3>
      <p></p>
      <h5><%= company_link(attendee) %></h5>

      <% if is_current_attendee?(attendee) -%>
        <p><%= link_to t('.update_profile'), edit_attendee_path %></p>
      <% end -%>

      <div class="list4 clearfix">
        <% unless attendee.city.blank? -%>
          <div>City</div>
          <div><%= content_tag(:strong, attendee.city) %></div>
        <% end -%>

        <% unless attendee.blog_url.blank? -%>
          <div>Blog</div>
          <div><%= link_to content_tag(:strong, attendee.blog_url), attendee.blog_url %></div>
        <% end -%>

        <% unless attendee.twitter_id.blank? -%>
          <div>Twitter</div>
          <div><%= twitter_link attendee.twitter_id %></div>
        <% end -%>

        <% unless attendee.github_id.blank? -%>
          <div>GitHub</div>
          <div><%= github_link attendee.github_id %></div>
        <% end -%>

        <% unless attendee.conference_sessions.empty? -%>
          <div>My Schedule</div>
          <div><%= link_to content_tag(:strong, t('.download_ical')), attendee_path(attendee, :format => :ics) %></div>
        <% end -%>
      </div>
      <h4 class="pad3"><%= t('.conference_schedule') %></h4>
      <%= render schedule_partial(attendee), :sessions => attendee.conference_sessions %>
    </div>
  </div>
</div>

app/views/attendees/_no_schedule.html.erb
<%= raw t('.no_schedule_yet') %>

app/views/attendees/_no_schedule_visitor.html.erb
<%= raw t('.no_schedule') %>

app/views/attendees/_populated_schedule.html.erb
<%= render 'shared/schedule' %>

app/views/attendees/edit.html.erb
<%= render :partial => 'shared/formtastic' %>
<%= render :partial => 'shared/title', :locals => { :title => t('.profile')}%>

<div class="container_12">
  <div class="grid_12">
    <%= semantic_form_for [current_attendee], :url => connect_update_path, :validate => true do |attendee_form| %>
    <%= attendee_form.inputs do %>
      <%= attendee_form.input :first_name, :label => t('.first_name') %>
      <%= attendee_form.input :middle_name, :label => t('.middle_name') %>
      <%= attendee_form.input :last_name, :label => t('.last_name') %>
      <%= attendee_form.input :city, :label => t('.city') %>
      <%= attendee_form.input :country, :label => t('.country'),
        :as => :select, :collection => Carmen::country_names %>
      <%= attendee_form.input :email, :label => t('.email'), :hint => t('.email_hint') %>
      <%= attendee_form.input :company, :label => t('.company') %>
      <%= attendee_form.input :company_url, :label => t('.company_url') %>
      <%= attendee_form.input :twitter_id, :label => t('.twitter_id'), :hint => t('.twitter_hint') %>
      <%= attendee_form.input :github_id, :label => t('.github_id'), :hint => t('.github_hint') %>
      <%= attendee_form.input :blog_url, :label => t('.blog_url') %>
    <% end %>
    <%= attendee_form.buttons do %>
      <%= attendee_form.commit_button :label => t('.commit')%>
    <% end %>
  <% end %>
  </div>
</div>

app/views/attendees/index.html.erb
<%= render 'shared/title', :title => t('.attendees') %>

<div id="main" class="shape">
  <div class="container_12 pad3">

  <% current_year_attendees.each_slice(4) do |attendees| -%>
    <div class="overflow p3">
      <% attendees.each do |attendee| -%>
      <div class="grid_3 speaker">
        <%= image_tag attendee.gravatar_url, :class => 'pic_speaker' %>
        <div style="float: left;">
          <h4><%= link_to attendee.full_name, attendee_path(attendee) %></h4>
          <h5><%= company_link(attendee) %></h5>
          <%= twitter_link attendee.twitter_id, :span %>
        </div>
      </div>
      <% end -%>
    </div>
  <% end -%>
  <%= will_paginate current_year_attendees, :previous_label => '', :next_label => '' %>

 </div>
</div>

app/views/attendees/show.html.erb
<%= render attendee %>

app/views/attendees/update.html.erb
<%= render attendee %>