config/routes.rb
#- Copyright 2011 Strange Loop LLC
#-
#- Licensed under the Apache License, Version 2.0 (the "License");
#- you may not use this file except in compliance with the License.
#- You may obtain a copy of the License at
#-
#-    http://www.apache.org/licenses/LICENSE-2.0
#-
#- Unless required by applicable law or agreed to in writing, software
#- distributed under the License is distributed on an "AS IS" BASIS,
#- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#- See the License for the specific language governing permissions and
#- limitations under the License.
#-



Conf::Application.routes.draw do


  devise_for :attendee_creds, :controllers => { :registrations => 'attendee_cred/registrations' } do
    get '/login' => 'devise/sessions#new', :as => :new_attendee_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_attendee_session
    get '/activation/:token', :to => 'devise/registrations#new', :as => :activation
    match '/connect' => 'attendees#index', :as => :attendee_cred_root
  end

  resource :attendee, :only => [:edit]
  resources :attendees, :only => [:index], :path => "/connect"
  resources :talks

  get '/stream', :to => 'stream#show'
  get '/streamtheater', :to => 'stream_theater#show'

  put '/connect/update', :to => 'attendees#update'
  get '/connect/:id', :to => 'attendees#show', :as => :attendee

  match '/media/*dragonfly', :to => Dragonfly[:strangeloop]

  match '/blog/:year/:month/:day/:id' => redirect('/news/%{year}/%{month}/%{day}/%{id}')
  match '/news/:year/:month/:day/:id' => 'news_items#show'
  match '/blog/stloopadm' => redirect('/news')
  match '/blog' => redirect('/news')



end

app/views/admin/news_items/_locale_picker.html.erb
<input type='hidden' name='switch_locale' id='switch_locale' value='<%= local_assigns[:current_locale] %>' />
<% if (locales ||= (defined?(::Refinery::I18n) && ::Refinery::I18n.frontend_locales)).present? and locales.many? %>
  <ul id='switch_locale_picker' class='clearfix'>
    <% locales.each do |locale| %>
      <li<%= " class='selected'" if locale.to_s == local_assigns[:current_locale].to_s %>>
        <%= link_to refinery_icon_tag("flags/#{locale}.png", :size => '48x33'),
                    url_for(:switch_locale => locale) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/news_items/_news_item.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= news_item.title %>
    <span class="preview">
      <%= t('.published') %> <%= l(news_item.publish_date, :format => :short) %>
    </span>
    <% if defined?(::Refinery::I18n) && ::Refinery::I18n.frontend_locales.many? and
          (locales = news_item.translations.collect{|t| t.locale}).present? %>
      <span class='preview'>
        <% locales.each do |locale| %>
          <%= refinery_icon_tag "flags/#{locale}.png", :size => '16x11' %>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_go.png'), news_item_url(news_item),
                :title => t('.view_live_html'),
                :target => "_blank" %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_news_item_path(news_item),
                :title => t('.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_news_item_path(news_item),
                :class => "cancel confirm-delete",
                :title => t('.delete'),
                :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => news_item.title) %>
  </span>
</li>